import type { MenuItem } from './MenuItem.ts'

import type { Demo } from './demos/Demo.ts'

import { DemoAreaHome } from './demos/DemoAreaHome.ts'

import { DemoAreaSingleHex } from './demos/DemoAreaSingleHex.ts'

import { DemoAreaXDominatedGrid } from './demos/DemoAreaXDominatedGrid.ts'

import { DemoAreaYDominatedGrid } from './demos/DemoAreaYDominatedGrid.ts'

export class DemoArea {
  private readonly element: HTMLElement

  private readonly heading: HTMLHeadingElement

  private readonly description: HTMLParagraphElement

  private readonly demoContainer: HTMLDivElement

  constructor() {
    this.element = document.createElement('main')

    this.element.className = 'demo-area'

    this.heading = document.createElement('h2')

    this.heading.className = 'demo-heading'

    this.description = document.createElement('p')

    this.description.className = 'demo-description'

    this.demoContainer = document.createElement('div')

    this.demoContainer.className = 'demo-container'

    this.element.append(
      this.heading,
      this.description,
      this.demoContainer
    )
  }

  public render(): HTMLElement {
    return this.element
  }

  public show(item: MenuItem): void {
    this.heading.textContent = item.label

    this.description.textContent =
      this.getDescription(item)

    const demo = this.createDemo(item)

    if (demo === null) {
      this.demoContainer.replaceChildren()

      return
    }

    this.demoContainer.replaceChildren(
      demo.render()
    )
  }

  private createDemo(item: MenuItem): Demo | null {
    if (item.id === 'home') {
      return new DemoAreaHome()
    }

    if (item.id === 'single-hex') {
      return new DemoAreaSingleHex()
    }

    if (item.id === 'x-dominated-grid') {
      return new DemoAreaXDominatedGrid()
    }

    if (item.id === 'y-dominated-grid') {
      return new DemoAreaYDominatedGrid()
    }

    return null
  }

  private getDescription(item: MenuItem): string {
    if (item.id === 'home') {
      return 'Select a demo from the menu to get started.'
    }

    if (item.id === 'single-hex') {
      return 'Single hexagons generated by the Midgard Hex Grid library.'
    }

    if (item.id === 'x-dominated-grid') {
      return 'A Midgard x-dominated hex grid generated from a 3 by 2 skeleton.'
    }

    if (item.id === 'y-dominated-grid') {
      return 'A Midgard y-dominated hex grid generated from a 3 by 2 skeleton.'
    }

    return 'This demo has not been implemented yet.'
  }
}