import type { MenuItem } from './MenuItem.ts'
import { HexGrid } from 'midgard-hex-grid'

export class DemoArea {
  private readonly element: HTMLElement

  private readonly heading: HTMLHeadingElement

  private readonly description: HTMLParagraphElement

  constructor() {
    this.element = document.createElement('main')
    this.element.className = 'demo-area'

    this.heading = document.createElement('h2')
    this.heading.className = 'demo-heading'

    this.description = document.createElement('p')
    this.description.className = 'demo-description'

    this.element.append(this.heading, this.description)
  }

  public render(): HTMLElement {
    return this.element
  }

  public show(item: MenuItem): void {
    this.heading.textContent = item.label
    this.description.textContent = this.getDescription(item)

    this.removeCurrentDemo()

    if (item.id === 'single-hex') {
      this.showSingleHexagons()
    }
  }

  private getDescription(item: MenuItem): string {
    if (item.id === 'home') {
      return 'Select a demo from the menu to get started.'
    }

    if (item.id === 'single-hex') {
      return 'Single hexagons generated by the Midgard Hex Grid library.'
    }

    return 'This demo has not been implemented yet.'
  }

  private removeCurrentDemo(): void {
    const currentDemo = this.element.querySelector('.demo-content-wrapper')

    if (currentDemo !== null) {
      currentDemo.remove()
    }
  }

  private showSingleHexagons(): void {
    const wrapper = document.createElement('div')
    wrapper.className = 'demo-content-wrapper'

    const xHeading = document.createElement('h3')
    xHeading.textContent = 'X-Dominated Hexagon'

    const xDescription = document.createElement('p')
    xDescription.textContent =
      'The width is specified by the user. The height is calculated automatically.'

    const xDemo = this.createXDominatedHexagon()

    const yHeading = document.createElement('h3')
    yHeading.textContent = 'Y-Dominated Hexagon'

    const yDescription = document.createElement('p')
    yDescription.textContent =
      'The height is specified by the user. The width is calculated automatically.'

    const yDemo = this.createYDominatedHexagon()

    wrapper.append(
      xHeading,
      xDescription,
      xDemo,
      yHeading,
      yDescription,
      yDemo
    )

    this.element.append(wrapper)
  }

  private createXDominatedHexagon(): HTMLDivElement {
    const grid = new HexGrid('x-dominated')

    const width = 300
    const height = (width * 2) / Math.sqrt(3)

    const center = {
      x: width / 2,
      y: height / 2
    }

    const points = grid.getHexagonPoints(
      center,
      width
    )

    return this.createHexagonSvg(
      points,
      width,
      height
    )
  }

  private createYDominatedHexagon(): HTMLDivElement {
    const grid = new HexGrid('y-dominated')

    const height = 300
    const width = (height * 2) / Math.sqrt(3)

    const center = {
      x: width / 2,
      y: height / 2
    }

    const points = grid.getHexagonPoints(
      center,
      height
    )

    return this.createHexagonSvg(
      points,
      width,
      height
    )
  }

  private createHexagonSvg(
    points: { x: number; y: number }[],
    width: number,
    height: number
  ): HTMLDivElement {
    const demoContent = document.createElement('div')
    demoContent.className = 'demo-content'

    const svg = document.createElementNS(
      'http://www.w3.org/2000/svg',
      'svg'
    )

    svg.setAttribute(
      'viewBox',
      `0 0 ${width} ${height}`
    )

    svg.setAttribute('width', width.toString())
    svg.setAttribute('height', height.toString())

    const polygon = document.createElementNS(
      'http://www.w3.org/2000/svg',
      'polygon'
    )

    const svgPoints = points
      .map((point) => `${point.x},${point.y}`)
      .join(' ')

    polygon.setAttribute('points', svgPoints)
    polygon.setAttribute('fill', 'none')
    polygon.setAttribute('stroke', 'currentColor')
    polygon.setAttribute('stroke-width', '3')

    svg.append(polygon)
    demoContent.append(svg)

    return demoContent
  }
}