import type { Demo } from './Demo.ts'

import {
  HexGrid
} from 'midgard-hex-grid'

import type {
  LayeredHexagon
} from 'midgard-hex-grid'

export class DemoAreaYDominatedGrid implements Demo {

  public render(): HTMLElement {
    const wrapper = document.createElement('div')

    wrapper.className = 'demo-content-wrapper'

    const heading = document.createElement('h3')

    heading.textContent = '3 × 2 Skeleton'

    const description = document.createElement('p')

    description.textContent =
      'The grid starts with a 3 × 2 skeleton and automatically fills around it.'

    const codeExample = this.createCodeExample(
      `const grid = new HexGrid('y-dominated')

const hexagons = grid.createGrid({
  hexDiameter: 100,
  skeletonWidth: 3,
  skeletonHeight: 2
})`
    )

    const grid = new HexGrid('y-dominated')

    const hexagons = grid.createGrid({
      hexDiameter: 100,
      skeletonWidth: 3,
      skeletonHeight: 2
    })

    const gridDemo = this.createGridSvg(
      hexagons
    )

    const resultHeading = document.createElement('h3')

    resultHeading.textContent =
      'Coordinates generated by the library'

    const coordinateList = document.createElement('pre')

    coordinateList.textContent = hexagons
      .map((hexagon) => {
        return `(${hexagon.coordinate.x}, ${hexagon.coordinate.y})  z-index: ${hexagon.zIndex}`
      })
      .join('\n')

    wrapper.append(
      heading,
      description,
      codeExample,
      gridDemo,
      resultHeading,
      coordinateList
    )

    return wrapper
  }

  private createCodeExample(
    code: string
  ): HTMLDivElement {
    const container = document.createElement('div')

    const heading = document.createElement('h4')

    heading.textContent = 'Library usage'

    const codeElement = document.createElement('pre')

    codeElement.textContent = code

    container.append(
      heading,
      codeElement
    )

    return container
  }

  private createGridSvg(
    hexagons: LayeredHexagon[]
  ): HTMLDivElement {
    const demoContent = document.createElement('div')

    demoContent.className = 'demo-content'

    const points = hexagons.flatMap(
      (hexagon) => hexagon.points
    )

    const xValues = points.map(
      (point) => point.x
    )

    const yValues = points.map(
      (point) => point.y
    )

    const minX = Math.min(...xValues)
    const maxX = Math.max(...xValues)
    const minY = Math.min(...yValues)
    const maxY = Math.max(...yValues)

    const width = maxX - minX
    const height = maxY - minY

    const svg = document.createElementNS(
      'http://www.w3.org/2000/svg',
      'svg'
    )

    svg.setAttribute(
      'viewBox',
      `${minX} ${minY} ${width} ${height}`
    )

    svg.setAttribute(
      'width',
      width.toString()
    )

    svg.setAttribute(
      'height',
      height.toString()
    )

    for (const hexagon of hexagons) {
      const polygon = document.createElementNS(
        'http://www.w3.org/2000/svg',
        'polygon'
      )

      const svgPoints = hexagon.points
        .map((point) => `${point.x},${point.y}`)
        .join(' ')

      polygon.setAttribute(
        'points',
        svgPoints
      )

      polygon.setAttribute(
        'fill',
        'none'
      )

      polygon.setAttribute(
        'stroke',
        'currentColor'
      )

      polygon.setAttribute(
        'stroke-width',
        '2'
      )

      svg.append(polygon)
    }

    demoContent.append(svg)

    return demoContent
  }
}